<?php
// 登陆控制器
Route::get('/', 'LoginController@index');
Route::post('/login', 'LoginController@login');
Route::get('/exit', 'LoginController@exit');
// 主页
Route::get('/home', 'HomeController@home');

// 公司管理 ********************************************************************************
  // 校区设置
      // 查看校区
      Route::get('/company/department', 'Company\DepartmentController@department');
      // 添加校区
      Route::get('/company/department/create', 'Company\DepartmentController@departmentCreate');
      // 保存校区
      Route::post('/company/department/store', 'Company\DepartmentController@departmentStore');
      // 修改校区
      Route::get('/company/department/edit', 'Company\DepartmentController@departmentEdit');
      // 更新校区
      Route::post('/company/department/update', 'Company\DepartmentController@departmentUpdate');
      // 删除校区
      Route::get('/company/department/delete', 'Company\DepartmentController@departmentDelete');
  // 课程设置
      // 查看课程
      Route::get('/company/course', 'Company\CourseController@course');
      // 添加课程
      Route::get('/company/course/create', 'Company\CourseController@courseCreate');
      // 保存课程
      Route::post('/company/course/store', 'Company\CourseController@courseStore');
      // 修改课程
      Route::get('/company/course/edit', 'Company\CourseController@courseEdit');
      // 更新课程
      Route::post('/company/course/update', 'Company\CourseController@courseUpdate');
      // 删除课程
      Route::get('/company/course/delete', 'Company\CourseController@courseDelete');
  // 教室设置
      // 查看教室
      Route::get('/company/classroom', 'Company\ClassroomController@classroom');
      // 添加教室
      Route::get('/company/classroom/create', 'Company\ClassroomController@classroomCreate');
      // 保存教室
      Route::post('/company/classroom/store', 'Company\ClassroomController@classroomStore');
      // 修改教室
      Route::get('/company/classroom/edit', 'Company\ClassroomController@classroomEdit');
      // 更新教室
      Route::post('/company/classroom/update', 'Company\ClassroomController@classroomUpdate');
      // 删除教室
      Route::get('/company/classroom/delete', 'Company\ClassroomController@classroomDelete');
  // 部门设置
      // 查看部门
      Route::get('/company/section', 'Company\SectionController@section');
      // 添加部门
      Route::get('/company/section/create', 'Company\SectionController@sectionCreate');
      // 保存部门
      Route::post('/company/section/store', 'Company\SectionController@sectionStore');
      // 修改部门
      Route::get('/company/section/edit', 'Company\SectionController@sectionEdit');
      // 更新部门
      Route::post('/company/section/update', 'Company\SectionController@sectionUpdate');
      // 删除部门
      Route::get('/company/section/delete', 'Company\SectionController@sectionDelete');
      // 添加岗位
      Route::get('/company/position/create', 'Company\SectionController@positionCreate');
      // 保存岗位
      Route::post('/company/position/store', 'Company\SectionController@positionStore');
      // 修改岗位
      Route::get('/company/position/edit', 'Company\SectionController@positionEdit');
      // 更新岗位
      Route::post('/company/position/update', 'Company\SectionController@positionUpdate');
      // 删除岗位
      Route::get('/company/position/delete', 'Company\SectionController@positionDelete');

// 人事中心 ********************************************************************************
  // 用户管理
      // 查看用户
      Route::get('/humanResource/user', 'HumanResource\UserController@user');
      // 添加用户
      Route::get('/humanResource/user/create', 'HumanResource\UserController@userCreate');
      // 保存用户
      Route::post('/humanResource/user/store', 'HumanResource\UserController@userStore');
      // 用户离职
      Route::get('/humanResource/user/delete', 'HumanResource\UserController@userDelete');
      // 用户权限
      Route::get('/humanResource/user/access', 'HumanResource\UserController@userAccess');
      // 更新权限
      Route::post('/humanResource/user/access/update', 'HumanResource\UserController@userAccessUpdate');
      // 密码恢复
      Route::get('/humanResource/user/password/restore', 'HumanResource\UserController@userPasswordRestore');
  // 面试用户
      // 查看面试用户
      Route::get('/humanResource/candidate', 'HumanResource\CandidateController@candidate');
      // 添加面试用户
      Route::get('/humanResource/candidate/create', 'HumanResource\CandidateController@candidateCreate');
      // 存储面试用户
      Route::post('/humanResource/candidate/store', 'HumanResource\CandidateController@candidateStore');
      // 查看面试用户简历
      Route::get('/humanResource/candidate/resume', 'HumanResource\CandidateController@candidateResume');
      // 面试用户转正
      Route::get('/humanResource/candidate/upgrade', 'HumanResource\CandidateController@candidateUpgrade');
      // 面试用户转正存储
      Route::post('/humanResource/candidate/upgrade/store', 'HumanResource\CandidateController@candidateUpgradeStore');
      // 面试用户删除
      Route::get('/humanResource/candidate/delete', 'HumanResource\CandidateController@candidateDelete');
  // 离职用户
      // 查看离职用户
      Route::get('/humanResource/user/deleted', 'HumanResource\UserDeletedController@userDeleted');
      // 恢复离职用户
      Route::get('/humanResource/user/deleted/restore', 'HumanResource\UserDeletedController@userDeletedRestore');
  // 用户档案
      // 查看用户档案
      Route::get('/humanResource/archive', 'HumanResource\ArchiveController@archive');
      // 查看用户上课记录
      Route::get('/humanResource/archive/lesson', 'HumanResource\ArchiveController@archiveLesson');
      // 查看用户签约记录
      Route::get('/humanResource/archive/contract', 'HumanResource\ArchiveController@archiveContract');
      // 查看用户动态
      Route::get('/humanResource/archive/record', 'HumanResource\ArchiveController@archiveRecord');
      // 查看用户档案文件
      Route::get('/humanResource/archive/archive', 'HumanResource\ArchiveController@archiveArchive');


// 招生中心 ********************************************************************************
    // 未签约学生
        // 查看未签约学生
        Route::get('/market/customer', 'Market\CustomerController@customer');
        // 添加新未签约学生
        Route::get('/market/customer/create', 'Market\CustomerController@customerCreate');
        Route::post('/market/customer/store', 'Market\CustomerController@customerStore');
        Route::get('/market/customer/success', 'Market\CustomerController@customerSuccess');
        // 未签约学生删除
        Route::get('/market/customer/delete', 'Market\CustomerController@customerDelete');
        // 签约合同
        Route::get('/market/customer/contract/create', 'Market\CustomerController@customerContractCreate');
        Route::post('/market/customer/contract/store', 'Market\CustomerController@customerContractStore');
        Route::get('/market/customer/contract/success', 'Market\CustomerController@customerContractSuccess');
    // 学生管理
        // 查看学生管理
        Route::get('/market/student', 'Market\StudentController@student');
        // 学生删除(转为离校)
        Route::get('/market/student/delete', 'Market\StudentController@studentDelete');
        // 签约合同
        Route::get('/market/student/contract/create', 'Market\StudentController@studentContractCreate');
        Route::post('/market/student/contract/store', 'Market\StudentController@studentContractStore');
        Route::get('/market/student/contract/success', 'Market\StudentController@studentContractSuccess');
    // 签约管理
        // 查看签约管理
        Route::get('/market/contract', 'Market\ContractController@contract');
        // 删除签约
        Route::get('/market/contract/delete', 'Market\ContractController@contractDelete');
        // 补缴
        Route::get('/market/contract/edit', 'Market\ContractController@contractEdit');
        Route::post('/market/contract/update', 'Market\ContractController@contractUpdate');

// 运营中心 ********************************************************************************
    // 学生管理
        // 查看学生管理
        Route::get('/operation/student', 'Operation\StudentController@student');
        // 学生删除(转为离校)
        Route::get('/operation/student/delete', 'Operation\StudentController@studentDelete');
        // 学生一对一排课
        Route::get('/operation/student/schedule/create', 'Operation\StudentController@studentScheduleCreate');
        Route::post('/operation/student/schedule/create2', 'Operation\StudentController@studentScheduleCreate2');
        Route::post('/operation/student/schedule/store', 'Operation\StudentController@studentScheduleStore');
        Route::get('/operation/student/schedule/success', 'Operation\StudentController@studentScheduleCreateSuccess');
        // 签约合同
        Route::get('/operation/student/contract/create', 'Operation\StudentController@studentContractCreate');
        Route::post('/operation/student/contract/store', 'Operation\StudentController@studentContractStore');
        Route::get('/operation/student/contract/success', 'Operation\StudentController@studentContractSuccess');
        // 年级升降
        Route::get('/operation/student/grade', 'Operation\StudentController@studentGrade');
        Route::post('/operation/student/grade/store', 'Operation\StudentController@studentGradeStore');
        // 转校区
        Route::get('/operation/student/department', 'Operation\StudentController@studentDepartment');
        Route::get('/operation/student/user', 'Operation\StudentController@studentUser');
        Route::post('/operation/student/department/store', 'Operation\StudentController@studentDepartmentStore');
    // 学生课时
        // 查看学生课时
        Route::get('/operation/hour', 'Operation\HourController@hour');
        // 学生退费
        Route::get('/operation/hour/refund/create', 'Operation\HourController@refundCreate');
        Route::post('/operation/hour/refund/store', 'Operation\HourController@refundStore');
        Route::get('/operation/hour/refund/delete', 'Operation\HourController@refundDelete');
        // 课时修改
        Route::get('/operation/hour/edit', 'Operation\HourController@hourEdit');
        Route::post('/operation/hour/update', 'Operation\HourController@hourUpdate');
    // 班级管理
        // 查看班级管理
        Route::get('/operation/class', 'Operation\ClassController@class');
        // 新建班级
        Route::get('/operation/class/create', 'Operation\ClassController@classCreate');
        Route::post('/operation/class/store', 'Operation\ClassController@classStore');
        // 删除班级
        Route::get('/operation/class/delete', 'Operation\ClassController@classDelete');
        // 班级排课
        Route::get('/operation/class/schedule/create', 'Operation\ClassController@classScheduleCreate');
        Route::post('/operation/class/schedule/create2', 'Operation\ClassController@classScheduleCreate2');
        Route::post('/operation/class/schedule/store', 'Operation\ClassController@classScheduleStore');
        Route::get('/operation/class/schedule/success', 'Operation\ClassController@classScheduleCreateSuccess');
    // 课程安排
    Route::get('/operation/schedule', 'Operation\ScheduleController@schedule');
        // 课程安排删除
        Route::get('/operation/schedule/delete', 'Operation\ScheduleController@scheduleDelete');
        // 点名
        Route::get('/operation/schedule/attend', 'Operation\ScheduleController@scheduleAttend');
        Route::post('/operation/schedule/attend/store', 'Operation\ScheduleController@scheduleAttendStore');
        Route::get('/operation/schedule/attend/success', 'Operation\ScheduleController@scheduleAttendSuccess');
    // 上课记录
        Route::get('/operation/attendedSchedule', 'Operation\AttendedScheduleController@attendedSchedule');
        // 上课记录删除
        Route::get('/operation/attendedSchedule/delete', 'Operation\AttendedScheduleController@attendedScheduleDelete');
    // 课程表
        // 周表
        Route::get('/operation/calendar/week', 'Operation\CalendarController@calendarWeek');
        // 日表
        Route::get('/operation/calendar/day', 'Operation\CalendarController@calendarDay');
    // 签约管理
        Route::get('/operation/contract', 'Operation\ContractController@contract');
        // 删除签约
        Route::get('/operation/contract/delete', 'Operation\ContractController@contractDelete');
        // 补缴
        Route::get('/operation/contract/edit', 'Operation\ContractController@contractEdit');
        Route::post('/operation/contract/update', 'Operation\ContractController@contractUpdate');
    // 退费管理
        Route::get('/operation/refund', 'Operation\RefundController@refund');
        // 退费删除
        Route::get('/operation/refund/delete', 'Operation\RefundController@refundDelete');
  // 离校学生
      // 查看离校学生
      Route::get('/operation/student/deleted', 'Operation\StudentDeletedController@studentDeleted');
      // 离校学生恢复
      Route::get('/operation/student/deleted/restore', 'Operation\StudentDeletedController@studentDeletedRestore');
      // 离校学生删除
      Route::get('/operation/student/deleted/delete', 'Operation\StudentDeletedController@studentDeletedDelete');

// 教学中心
    // 学生管理
        Route::get('/education/student', 'Education\StudentController@student');
    // 班级管理
        Route::get('/education/class', 'Education\ClassController@class');
    // 课程安排
        Route::get('/education/schedule', 'Education\ScheduleController@schedule');
    // 上课记录
    Route::get('/education/attendedSchedule', 'Education\AttendedScheduleController@attendedSchedule');
    // 课程表
        // 周表
        Route::get('/education/calendar/week', 'Education\CalendarController@calendarWeek');
        // 周表
        Route::get('/education/calendar/day', 'Education\CalendarController@calendarDay');
    // 教案中心
        // 查看教案中心
        Route::get('/education/document', 'Education\DocumentController@document');
        // 上传教案
        Route::get('/education/document/create', 'Education\DocumentController@documentCreate');
        Route::post('/education/document/store', 'Education\DocumentController@documentStore');
        // 下载教案
        Route::get('/education/document/download', 'Education\DocumentController@documentDownload');
        // 删除教案
        Route::get('/education/document/delete', 'Education\DocumentController@documentDelete');

// 数据中心
    // 部门签约明细
    Route::get('/finance/contract/department', 'Finance\ContractController@contractDepartment');
    // 个人签约明细
    Route::get('/finance/contract/user', 'Finance\ContractController@contractUser');
    // 部门课消明细
    Route::get('/finance/consumption/department', 'Finance\ConsumptionController@consumptionDepartment');
    // 个人课消明细
    Route::get('/finance/consumption/user', 'Finance\ConsumptionController@consumptionUser');

// 个人中心 ********************************************************************************
    // 我的未签约学生
        // 查看我的未签约学生
        Route::get('/self/customer', 'Self\CustomerController@customer');
        // 添加新未签约学生
        Route::get('/self/customer/create', 'Self\CustomerController@customerCreate');
        Route::post('/self/customer/store', 'Self\CustomerController@customerStore');
        Route::get('/self/customer/success', 'Self\CustomerController@customerSuccess');
        // 未签约学生删除
        Route::get('/self/customer/delete', 'Self\CustomerController@customerDelete');
        // 签约合同
        Route::get('/self/customer/contract/create', 'Self\CustomerController@customerContractCreate');
        Route::post('/self/customer/contract/store', 'Self\CustomerController@customerContractStore');
        Route::get('/self/customer/contract/success', 'Self\CustomerController@customerContractSuccess');
    // 我的学生(课程顾问)
        // 查看我的学生（课程顾问）
        Route::get('/self/consultant/student', 'Self\ConsultantStudentController@student');
        // 签约合同
        Route::get('/self/consultant/student/contract/create', 'Self\ConsultantStudentController@studentContractCreate');
        Route::post('/self/consultant/student/contract/store', 'Self\ConsultantStudentController@studentContractStore');
        Route::get('/self/consultant/student/contract/success', 'Self\ConsultantStudentController@studentContractSuccess');
    // 我的学生（班主任）
        // 查看我的学生（班主任）
        Route::get('/self/adviser/student', 'Self\AdviserStudentController@student');
        // 学生一对一排课
        Route::get('/self/adviser/student/schedule/create', 'Self\AdviserStudentController@studentScheduleCreate');
        Route::post('/self/adviser/student/schedule/create2', 'Self\AdviserStudentController@studentScheduleCreate2');
        Route::post('/self/adviser/student/schedule/store', 'Self\AdviserStudentController@studentScheduleStore');
        Route::get('/self/adviser/student/schedule/success', 'Self\AdviserStudentController@studentScheduleCreateSuccess');
        // 签约合同
        Route::get('/self/adviser/student/contract/create', 'Self\AdviserStudentController@studentContractCreate');
        Route::post('/self/adviser/student/contract/store', 'Self\AdviserStudentController@studentContractStore');
        Route::get('/self/adviser/student/contract/success', 'Self\AdviserStudentController@studentContractSuccess');



// 用户详情
Route::get('/user', 'UserController@user');
    // 用户动态
    Route::post('/user/record', 'UserController@record');
    // 用户档案上传
    Route::post('/user/archive', 'UserController@archive');
    // 修改用户
    Route::get('/user/edit', 'UserController@edit');
    // 更新用户
    Route::post('/user/update', 'UserController@update');


// 面试用户详情
Route::get('/candidate', 'CandidateController@candidate');
    // 面试用户动态
    Route::post('/candidate/record', 'CandidateController@record');
    // 修改面试用户
    Route::get('/candidate/edit', 'CandidateController@candidateEdit');
    // 更新面试用户
    Route::post('/candidate/update', 'CandidateController@candidateUpdate');

// 学生详情
Route::get('/student', 'StudentController@student');
    // 修改学生
    Route::post('/student/update', 'StudentController@update');
    // 学生备注提交
    Route::post('/student/remark', 'StudentController@remark');
    // 学生跟进记录提交
    Route::post('/student/record', 'StudentController@record');
    // 插入班级
    Route::post('/student/member/add', 'StudentController@memberAdd');
    // 退出班级
    Route::get('/student/member/delete', 'StudentController@memberDelete');

// 班级详情
Route::get('/class', 'ClassController@class');
    // 修改班级
    Route::post('/class/update', 'ClassController@update');
    // 添加成员
    Route::post('/class/member/add', 'ClassController@memberAdd');
    // 删除成员
    Route::get('/class/member/delete', 'ClassController@memberDelete');

// 查看合同
Route::get('/contract', 'ContractController@show');

// 个人信息
Route::get('/profile', 'ProfileController@show');
Route::post('/profile/password/update', 'ProfileController@passwordUpdate');

